version: "3.8"

services:
  neo4j:
    image: neo4j:5.24.1
    volumes:
      - type: bind
        source: ./data/neo4j/data
        target: /data
      - type: bind
        source: ./data/neo4j/logs
        target: /logs
    ports:
      - 7474:7474
      - 7687:7687
    env_file: .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  argilla:
    # loosely adapted from
    # https://github.com/argilla-io/argilla/blob/a88c81879d7088413912e6c368eee8ae77e840a9/docker/docker-compose.yaml
    image: argilla/argilla-server:v1.26.1
    container_name: argilla
    restart: unless-stopped
    ports:
      - 6900:6900
    environment:
      ARGILLA_HOME_PATH: /var/lib/argilla
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
    env_file:
      - .env
    depends_on:
      - elasticsearch
    volumes:
      - argilla_data:/var/lib/argilla

  predictions_api:
    build:
      context: .
      dockerfile: predictions_api/Dockerfile
    ports:
      - 80:80
    volumes:
      # need to include aws credentials so that we can sync the data from S3
      - ~/.aws:/root/.aws
    env_file:
      - .env

volumes:
  elasticsearch_data:
  argilla_data:
