[tool.poetry]
name = "knowledge-graph"
version = "0.1.0"
description = ""
authors = ["CPR Data Science <dsci@climatepolicyradar.org>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{ include = "src", from = "." }]


[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.26.0"
rich = "^13.7.0"
tqdm = "^4.66.2"
ipykernel = "^6.29.3"
explorer = { git = "https://github.com/climatepolicyradar/explorer.git", rev = "96d2a244f4a0e3298a080f71edee6c4b96e5bd37" }
neomodel = "^5.2.1"
typer = "0.9.4"

[tool.poetry.group.dev.dependencies]
nbstripout = "^0.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
