name: concept-store-mcp
description: an MCP read-only interface to the concept store
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
