---
- wikibase_id: Q53
  concept_id: kgtd77zy
  classifier_id: r4xsb4ff
  classifiers_profile: experimental
  wandb_registry_version: v6
- wikibase_id: Q57
  concept_id: jhzt73ef
  classifier_id: jq7535b6
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q68
  concept_id: fbmdrtxs
  classifier_id: kk8dqcrj
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q69
  concept_id: fr8zmkz5
  classifier_id: bp3wqfwc
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q218
  concept_id: 7h7nwymz
  classifier_id: 3p7eyng3
  classifiers_profile: primary
  wandb_registry_version: v22
- wikibase_id: Q221
  concept_id: s9rbcnjc
  classifier_id: zahr3y3c
  classifiers_profile: primary
  wandb_registry_version: v15
  dont_run_on:
  - sabin
- wikibase_id: Q221
  concept_id: s9rbcnjc
  classifier_id: zahr3y3c
  classifiers_profile: primary
  wandb_registry_version: v16
- wikibase_id: Q223
  concept_id: fxx6vsts
  classifier_id: dntrzvg4
  classifiers_profile: primary
  wandb_registry_version: v15
- wikibase_id: Q226
  concept_id: fmp2rf6u
  classifier_id: epdr39n7
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q368
  concept_id: 7tehkdsa
  classifier_id: mfe6wvbv
  classifiers_profile: primary
  wandb_registry_version: v26
- wikibase_id: Q374
  concept_id: k5v9kwpz
  classifier_id: 2dpw38rj
  classifiers_profile: primary
  wandb_registry_version: v25
- wikibase_id: Q404
  concept_id: v639qc56
  classifier_id: fd5t9bhw
  classifiers_profile: primary
  wandb_registry_version: v25
- wikibase_id: Q412
  concept_id: nq7qed9f
  classifier_id: 9cfzu8vh
  classifiers_profile: primary
  wandb_registry_version: v29
- wikibase_id: Q572
  concept_id: 9z6466fd
  classifier_id: 9x5fdgft
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q601
  concept_id: ajmbjenf
  classifier_id: 76fhnpae
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q606
  concept_id: b7hq9sjw
  classifier_id: pun2by55
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q615
  concept_id: g2am6yeg
  classifier_id: 3wkwmd2t
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q618
  concept_id: 2xjs3h9k
  classifier_id: qp7pt7vc
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q622
  concept_id: hgp9qfdf
  classifier_id: gxgdn95e
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q639
  concept_id: 9a3aj2vs
  classifier_id: zp9e66p9
  classifiers_profile: primary
  wandb_registry_version: v15
- wikibase_id: Q650
  concept_id: rpjsztya
  classifier_id: 274gekg9
  classifiers_profile: primary
  wandb_registry_version: v12
- wikibase_id: Q661
  concept_id: 2t8g665t
  classifier_id: ty2jvjmp
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q676
  concept_id: qufgafbd
  classifier_id: y3vcj3dm
  classifiers_profile: primary
  wandb_registry_version: v16
- wikibase_id: Q684
  concept_id: z6atmpr5
  classifier_id: 9adt36v3
  classifiers_profile: primary
  wandb_registry_version: v19
- wikibase_id: Q690
  concept_id: 3mrsd5tt
  classifier_id: eq9x9wsr
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q695
  concept_id: jmrvstuy
  classifier_id: am4npkr4
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q701
  concept_id: jbk7m3h3
  classifier_id: nyutpxgp
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q704
  concept_id: gd8erujh
  classifier_id: y5npmjhs
  classifiers_profile: primary
  wandb_registry_version: v16
- wikibase_id: Q708
  concept_id: s5f84ek7
  classifier_id: x9kfsd8s
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q715
  concept_id: 3p6q6dvd
  classifier_id: hqv67qyk
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q757
  concept_id: fjt7qa5v
  classifier_id: n4t9ec5y
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q760
  concept_id: pdfdj93h
  classifier_id: fvdwz7cn
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q761
  concept_id: ay5xp6pp
  classifier_id: grw5x8ee
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q762
  concept_id: 2vha6wu7
  classifier_id: qa22cf6s
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q763
  concept_id: v7wgjjq5
  classifier_id: s3cc4cdt
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q764
  concept_id: t2kwx49y
  classifier_id: nxt8v557
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q765
  concept_id: rqvbs4ck
  classifier_id: mqmq7qz7
  classifiers_profile: primary
  wandb_registry_version: v25
- wikibase_id: Q766
  concept_id: f9ukm3xu
  classifier_id: auwqx2qx
  classifiers_profile: primary
  wandb_registry_version: v25
- wikibase_id: Q767
  concept_id: ynqpspj5
  classifier_id: dfk2cka7
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q768
  concept_id: c92ey235
  classifier_id: pgqzewd7
  classifiers_profile: primary
  wandb_registry_version: v23
- wikibase_id: Q769
  concept_id: bkd2e898
  classifier_id: 7cgtdjf8
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q774
  concept_id: s6dj54pk
  classifier_id: qxa74qvw
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q775
  concept_id: 97eec6yx
  classifier_id: z928v42x
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q777
  concept_id: qembqy8s
  classifier_id: 8fj9pk8h
  classifiers_profile: primary
  wandb_registry_version: v22
- wikibase_id: Q778
  concept_id: eum2twbb
  classifier_id: bgrd72hx
  classifiers_profile: primary
  wandb_registry_version: v22
- wikibase_id: Q779
  concept_id: suphkggg
  classifier_id: y5d5v37k
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q786
  concept_id: 3h5zaxzb
  classifier_id: e6mcjpw5
  classifiers_profile: primary
  wandb_registry_version: v22
- wikibase_id: Q787
  concept_id: jn3g8a9d
  classifier_id: esv3cdac
  classifiers_profile: primary
  wandb_registry_version: v27
- wikibase_id: Q788
  concept_id: fq8b5hg5
  classifier_id: 9pexe8zd
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q818
  concept_id: pwysykyb
  classifier_id: xtpdyp7t
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q856
  concept_id: 94fq5ub2
  classifier_id: rqtk7h47
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q857
  concept_id: 94fq5ub2
  classifier_id: 9hmkcj6h
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q954
  concept_id: aq8fj9um
  classifier_id: fyhqe7b6
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q955
  concept_id: ubnryyem
  classifier_id: cfuft4qg
  classifiers_profile: primary
  wandb_registry_version: v25
- wikibase_id: Q956
  concept_id: qyphhzrh
  classifier_id: 7dcdxgfj
  classifiers_profile: primary
  wandb_registry_version: v27
- wikibase_id: Q973
  concept_id: hxwedeq8
  classifier_id: 2nwj5fwh
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q983
  concept_id: djp6pwhu
  classifier_id: dsxc3m8e
  classifiers_profile: primary
  wandb_registry_version: v24
- wikibase_id: Q986
  concept_id: 6suvsrvj
  classifier_id: mjaupkch
  classifiers_profile: primary
  wandb_registry_version: v25
- wikibase_id: Q1016
  concept_id: 3mpujybt
  classifier_id: 6vn29j93
  classifiers_profile: primary
  wandb_registry_version: v16
- wikibase_id: Q1167
  concept_id: 2dwceyw2
  classifier_id: gq529aad
  classifiers_profile: primary
  wandb_registry_version: v16
- wikibase_id: Q1269
  concept_id: edzenmt9
  classifier_id: ruzvuy9d
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1273
  concept_id: n4d4mxs5
  classifier_id: 9aezptyn
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1274
  concept_id: t3585tjf
  classifier_id: wk49jsch
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1275
  concept_id: 9fcsmbqe
  classifier_id: bb55gpzc
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1276
  concept_id: mnzx57k6
  classifier_id: dp92w33k
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1277
  concept_id: 85nwxvcm
  classifier_id: smhdpm2v
  classifiers_profile: primary
  wandb_registry_version: v16
- wikibase_id: Q1278
  concept_id: vumks6ja
  classifier_id: 5b3ndxc3
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1279
  concept_id: 4p4bs69r
  classifier_id: 2he9rkha
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1280
  concept_id: bynmed25
  classifier_id: bhf4p2mt
  classifiers_profile: primary
  wandb_registry_version: v15
- wikibase_id: Q1281
  concept_id: 4n5r8s7c
  classifier_id: yvzajyqf
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1282
  concept_id: kghatay6
  classifier_id: z7cnc9cz
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1284
  concept_id: wxnjt4gd
  classifier_id: mxfwgjr7
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1285
  concept_id: yfd9f8q7
  classifier_id: 6pm6a6nd
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1286
  concept_id: c8rvrhqh
  classifier_id: 5rjgvetv
  classifiers_profile: primary
  wandb_registry_version: v14
- wikibase_id: Q1343
  concept_id: 22q362cd
  classifier_id: vax7e3n7
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1344
  concept_id: f3jxb2er
  classifier_id: g8veubg3
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1345
  concept_id: 3b635c3d
  classifier_id: wy3a2h5x
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1346
  concept_id: 8m9nendg
  classifier_id: aqrcdtxx
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1362
  concept_id: xn9vp8t3
  classifier_id: bugd7dbt
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1368
  concept_id: 6bbq9thx
  classifier_id: 9n9xsymu
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1369
  concept_id: xbfj5vfj
  classifier_id: wyaugrjm
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1370
  concept_id: qf5rwhnf
  classifier_id: 6dxvusb9
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1371
  concept_id: u9sz78pv
  classifier_id: v76y24qd
  classifiers_profile: primary
  wandb_registry_version: v13
- wikibase_id: Q1651
  concept_id: 2a4gwebb
  classifier_id: 6rys3abe
  classifiers_profile: primary
  wandb_registry_version: v13
  compute_environment:
    gpu: true
- wikibase_id: Q1652
  concept_id: 5edqv54g
  classifier_id: 57uwtz45
  classifiers_profile: primary
  wandb_registry_version: v10
  compute_environment:
    gpu: true
- wikibase_id: Q1653
  concept_id: set8cyd3
  classifier_id: u86a8p2d
  classifiers_profile: primary
  wandb_registry_version: v12
  compute_environment:
    gpu: true
- wikibase_id: Q1744
  concept_id: yvxkuenr
  classifier_id: ekzukwdz
  classifiers_profile: primary
  wandb_registry_version: v1
- wikibase_id: Q1754
  concept_id: h3u5pac7
  classifier_id: 36bb7tcv
  classifiers_profile: primary
  wandb_registry_version: v1
