import re
from datetime import datetime

import pytest

from flows.boundary import (
    DocumentObjectUri,
    load_labelled_passages_by_uri,
)
from knowledge_graph.labelled_passage import LabelledPassage
from knowledge_graph.span import Span
from tests.flows.conftest import load_fixture

DOCUMENT_PASSAGE_ID_PATTERN = re.compile(
    r"id:doc_search:document_passage::[a-zA-Z]+.[a-zA-Z]+.\d+.\d+.\d+"
)
DATA_ID_PATTERN = re.compile(r"[a-zA-Z]+.[a-zA-Z]+.\d+.\d+.\d+")


@pytest.mark.asyncio
async def test_load_labelled_passages_by_uri_obj(
    mock_async_bucket, mock_s3_async_client
):
    fixture = load_fixture(
        "labelled_passages/Q218/q4xsgmjb/AF.document.002MMUCR.n0003.json"
    )
    await mock_s3_async_client.put_object(
        Bucket=mock_async_bucket,
        Key="labelled_passages/Q218/q4xsgmjb/AF.document.002MMUCR.n0003.json",
        Body=fixture,
        ContentType="application/json",
    )

    document_object_uri: DocumentObjectUri = f"s3://{mock_async_bucket}/labelled_passages/Q218/q4xsgmjb/AF.document.002MMUCR.n0003.json"
    assert load_labelled_passages_by_uri(document_object_uri) == [
        LabelledPassage(
            id="308",
            text=". Demand Controlled Ventilation via CO2 sensors",
            spans=[
                Span(
                    text=". Demand Controlled Ventilation via CO2 sensors",
                    start_index=36,
                    end_index=39,
                    concept_id="Q218",
                    labellers=['KeywordClassifier("greenhouse gas")'],
                    timestamps=[datetime(2025, 2, 24, 18, 42, 12, 677997)],
                    id="fxdgkkmc",
                    labelled_text="CO2",
                )
            ],
            metadata={
                "concept": {
                    "preferred_label": "greenhouse gas",
                    "alternative_labels": [
                        "SLCP",
                        "SLCFs",
                        "short lived climate forcers",
                        "hexafluoride",
                        "short-lived climate forcer",
                        "perfluorocarbon",
                        "super pollutants",
                        "nitrogen trifluoride",
                        "CO2",
                        "short-lived climate pollutant",
                        "superpollutants",
                        "HFC",
                        "CFC",
                        "steam",
                        "Hydrofluorocarbon",
                        "CBrClF2",
                        "nitrous",
                        "PFC",
                        "GHG",
                        "freon",
                        "C2H3Cl2",
                        "emission of GHGs",
                        "F-gas",
                        "emissions of GHG",
                        "SLCPs",
                        "HCFCs",
                        "CH3Br",
                        "Halon 1211",
                        "Sulfur hexafluoride",
                        "CFCs",
                        "SFs",
                        "GHG emissions",
                        "carbon tetrachloride",
                        "green house gas emissions",
                        "carbon dioxide equivalent",
                        "aqueous vapor",
                        "carbon gas",
                        "greenhouse gas emissions",
                        "MBr",
                        "nitrous oxide",
                        "hydrochlorofluorocarbons",
                        "HCFC",
                        "CBrF3",
                        "tropospheric ozone",
                        "HFCs",
                        "CO2e",
                        "methyl bromide",
                        "short lived climate pollutants",
                        "GHGs emissions",
                        "CH4",
                        "short lived climate forcer",
                        "green house gases",
                        "SF6",
                        "hfos",
                        "F gas",
                        "methane",
                        "NF3",
                        "short lived climate pollutant",
                        "trifluoride",
                        "ch4",
                        "chlorofluorocarbons",
                        "short-lived climate forcers",
                        "halons",
                        "halon",
                        "carbon dioxide",
                        "CO₂",
                        "PFCs",
                        "Halon 1301",
                        "short-lived climate pollutants",
                        "black carbon",
                        "HFOs",
                        "SF",
                        "carbon tet",
                        "F gases",
                        "N2O",
                        "greenhouse gas",
                        "bromochlorodifluoromethane",
                        "hydrofluoroolefins",
                        "green house gas",
                        "ground-level ozone",
                        "O3",
                        "F-gases",
                        "fluorinated gas",
                        "sulphur hexafluoride",
                        "SLCF",
                        "water vapor",
                        "NFs",
                        "hydrochlorofluorocarbon",
                        "NF",
                        "methyl chloroform",
                        "CH₄",
                        "hydrofluorocarbons",
                        "GHGs",
                        "fluorinated gases",
                        "perfluorocarbons",
                        "bromotrifluoromethane",
                        "chlorofluorocarbon",
                        "greenhouse gases",
                    ],
                    "negative_labels": [],
                    "description": "Greenhouse gases are molecules in our atmosphere that absorb heat radiating from Earth’s surface, preventing it from being emitted into space.",
                    "wikibase_id": "Q218",
                    "subconcept_of": [],
                    "has_subconcept": [
                        "Q223",
                        "Q229",
                        "Q240",
                        "Q237",
                        "Q917",
                        "Q918",
                        "Q919",
                        "Q977",
                        "Q1009",
                        "Q731",
                        "Q732",
                        "Q922",
                        "Q221",
                    ],
                    "related_concepts": [
                        "Q232",
                        "Q560",
                        "Q753",
                        "Q221",
                        "Q978",
                        "Q1652",
                    ],
                    "definition": "Greenhouse gases are molecules in our atmosphere that absorb heat radiating from Earth’s surface, preventing it from being emitted into space. The most common greenhouse gases are (in order of atmospheric concentration) water vapor (H2O), carbon dioxide (CO2), methane (CH4), nitrous oxide (N2O), and a suite of halogen-bearing gases (like fluorocarbons) that are derived from industrial activities.",
                    "labelled_passages": [],
                }
            },
        ),
    ]


@pytest.mark.asyncio
async def test_load_labelled_passages_by_uri_raw(
    mock_async_bucket, mock_s3_async_client
):
    fixture = load_fixture(
        "labelled_passages/Q857/sd6wjpa2/AF.document.i00000021.n0000_translated_en.json"
    )
    await mock_s3_async_client.put_object(
        Bucket=mock_async_bucket,
        Key="labelled_passages/Q857/sd6wjpa2/AF.document.i00000021.n0000_translated_en.json",
        Body=fixture,
        ContentType="application/json",
    )

    document_object_uri: DocumentObjectUri = f"s3://{mock_async_bucket}/labelled_passages/Q857/sd6wjpa2/AF.document.i00000021.n0000_translated_en.json"
    assert load_labelled_passages_by_uri(document_object_uri) == [
        LabelledPassage(
            id="58",
            text="13. Projects/programmes supported by the Fund will provide fair, equitable and inclusive access to the expected benefits without hindering access to basic health services, safe water and sanitation, energy, education, housing, safe and decent working conditions and land rights. Projects/programmes should not deepen existing inequalities, particularly those affecting marginalized or vulnerable groups.",
            spans=[
                Span(
                    text="13. Projects/programmes supported by the Fund will provide fair, equitable and inclusive access to the expected benefits without hindering access to basic health services, safe water and sanitation, energy, education, housing, safe and decent working conditions and land rights. Projects/programmes should not deepen existing inequalities, particularly those affecting marginalized or vulnerable groups.",
                    start_index=155,
                    end_index=170,
                    concept_id="Q857",
                    labellers=['KeywordClassifier("healthcare sector")'],
                    timestamps=[datetime(2025, 2, 25, 1, 35, 56, 388056)],
                    id="b37t5esb",
                    labelled_text="health services",
                )
            ],
            metadata={
                "concept": {
                    "preferred_label": "healthcare sector",
                    "alternative_labels": [
                        "commercial healthcare sector",
                        "specialized hospital services",
                        "pharmaceutical manufacturing sector",
                        "mental health services",
                        "behavioural health service",
                        "family medicine",
                        "complex medical treatment",
                        "health prevention services",
                        "community heal services",
                        "emergency medical services",
                        "manufacture of pharmaceuticals",
                        "EMS",
                        "secondary care sector",
                        "health services industry",
                        "health services",
                        "health rehabilitation service",
                        "medical product distribution",
                        "specialized medical services",
                        "drug service",
                        "pharmaceutical industry",
                        "public medical services",
                        "general healthcare services",
                        "private health service",
                        "public health system",
                        "tertiary care service",
                        "speciality healthcare",
                        "preventive medicine",
                        "public health initiatives",
                        "pharmacy sector",
                        "private medical sector",
                        "public healthcare services management",
                        "specialist healthcare service",
                        "pharmaceutical production",
                        "private healthcare sector",
                        "medical care sector",
                        "alternative medicine",
                        "therapy service",
                        "complementary medicine",
                        "health rehabilitation services",
                        "privatised medical services",
                        "complementary therapy",
                        "private health system",
                        "medical services sector",
                        "pharmaceutical manufacturing",
                        "recovery support service",
                        "health service",
                        "Manufacture of basic pharmaceutical products",
                        "private health services",
                        "rehabilitative care",
                        "specialist healthcare services",
                        "pharmaceutical preparations",
                        "traditional healthcare practices",
                        "medicine production",
                        "urgent medical service",
                        "pharmaceutical care",
                        "healthcare system",
                        "primary healthcare system",
                        "mental wellness programs",
                        "medication management",
                        "public health provision",
                        "mental health service",
                        "integrative medicine",
                        "preventive healthcare",
                        "health sector",
                        "traditional healthcare practice",
                        "medicine industry",
                        "hospital care",
                        "mental healthcare",
                        "primary care services",
                        "medicine manufacturing",
                        "pharmaceutical processing",
                        "urgent medical response",
                        "health rehabilitation program",
                        "public healthcare management",
                        "drug services",
                        "emergency healthcare services",
                        "pharmaceutical sector",
                        "general healthcare service",
                        "clinical specialist services",
                        "complementary therapies",
                        "tertiary healthcare",
                        "traditional medicine",
                        "healthcare services",
                        "public health administration",
                        "secondary healthcare system",
                        "preventive medicine service",
                        "pharmaceutical products manufacturing",
                        "private health industry",
                        "private healthcare system",
                        "advanced medical care",
                        "healthcare industry",
                        "disease prevention strategy",
                    ],
                    "negative_labels": [],
                    "description": "This sector provides medical services, manufactures medical equipment, and develops pharmaceuticals to maintain and improve health.",
                    "wikibase_id": "Q857",
                    "subconcept_of": ["Q709"],
                    "has_subconcept": [
                        "Q1571",
                        "Q1641",
                        "Q1642",
                        "Q1643",
                        "Q1644",
                        "Q1645",
                        "Q1646",
                        "Q1647",
                        "Q806",
                        "Q1648",
                        "Q1650",
                    ],
                    "related_concepts": [
                        "Q1164",
                        "Q418",
                        "Q16",
                        "Q419",
                        "Q974",
                        "Q374",
                        "Q1601",
                        "Q1649",
                    ],
                    "definition": None,
                    "labelled_passages": [],
                }
            },
        )
    ]
