name: Bump dependencies

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run pre-commit autoupdate
        run: uv run pre-commit autoupdate

      - name: Detect changes
        id: changed-file
        run: |
          if git diff --quiet --exit-code .pre-commit-config.yaml; then
            echo "any_changed=false" >> $GITHUB_OUTPUT
          else
            echo "any_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changed-file.outputs.any_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: 'ci: Bump pre-commit hooks'
          body: |
            Update versions of tools in pre-commit
            configs to latest version
