name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

permissions:
  contents: write

jobs:
  deploy_prefect_labs:
    name: "Labs"
    if: |
      (github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main') ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: labs
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_LABS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_LABS }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

  deploy_prefect_staging:
    name: "Staging"
    if: |
      (github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main') ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: staging
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

  deploy_prefect_prod:
    name: "Prod"
    if: |
      (github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main') ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
