name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

permissions:
  contents: write

jobs:
  deploy_docs:
    # Currently disabled as it's failing and possibly isn't needed[1].
    #
    # [1] https://climate-policy-radar.slack.com/archives/C06JZKM6PGQ/p1745844798378639
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Deploy docs
        working-directory: ./docs
        run: uv run mkdocs gh-deploy --force

  deploy_prefect_sandbox:
    if: |
      (github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main') ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: sandbox
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

  deploy_prefect_labs:
    if: github.ref == 'refs/heads/main'
    needs: [deploy_prefect_sandbox]
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: labs
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_LABS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_LABS }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

  deploy_prefect_staging:
    if: github.ref == 'refs/heads/main'
    needs: [deploy_prefect_sandbox]
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: staging
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

  deploy_prefect_prod:
    if: github.ref == 'refs/heads/main'
    needs: [deploy_prefect_sandbox]
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
