name: "CD / Prefect / Staging"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy_prefect_staging:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/prefect_deploy.yml
    with:
      aws-env: staging
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
